### ISSUE TITLE
Bounds are wrong on multi-screen PCs

### ISSUE THREAD

**Issue by Zenopheus** [ideka/AugTyr#4] opened 2017-07-21 16:13 UTC
Thanks for AugTyr! I'm having some problems though...

I have two monitors. My primary monitor is 2560x1440 that I use to play GW2 and my secondary is 1600x900. It seems your code is using the secondary monitor resolution by mistake.

The first few times I used AugTry everything worked fine but for some reason AugTry is now compressed to 1600x900 on my **primary** monitor. Basically the nodes and lines are scrunched into the top left area of the screen. 

To test this I closed AugTry down and disabled the secondary windows then relaunched it. Surprisingly the issue remains, it is still assuming the primary monitor is 1600x900 instead of 2560x1440.

As a work around I can force the correct resolution via the Unity command line switches:
**AugTyr.exe -screen-width 2560 -screen-height 1440**

**Comment by ideka** [comment] 2017-07-21 20:35
Thanks for the report.

Sadly this is gonna be tricky to fix since I don't see myself reproducing the error, plus all that resolution stuff is Unity's job and not AugTyr's.

I'll keep this issue open and take note of the workaround for now. I'll se what can be done about it later.

**Comment by Zenopheus** [comment] 2017-07-21 20:42
No problem. I'm waiting for my job to update my unity license. Once i get a
chance i'll look into it. I didn't see anything obvious in the code.

**Comment by ideka** [comment] 2017-08-07 21:25
Resolution can be set via user config as of 068a4fb8becfaf0513834166497f8bc4f38792ac. Closing this issue.

**Closed as completed by ideka** 2017-08-07 21:25 UTC
